bottle/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mail.urls")),
    path("accounts/", include("allauth.urls")),
]

mail/urls.py
from django.urls import path
from . import views


app_name = "mail"
urlpatterns = [
    path('', views.BaseView.as_view(), name='home'),
    path('mail/', views.MailView.as_view(), name='mail'),
    path("mail/<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("mail/<int:pk>/like/", views.LikeView.as_view(), name="like"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):

    class Meta:
        verbose_name_plural = "ユーザー"

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Detail</h1>

<h3>title: {{ content.title }}</h3>
     <p>text: {{ content.text }}</p>
     <p>likes: {{ content.like_counter }}</p>
     <p>created_at: {{ content.created_at}}</p>
        <a href="{% url 'mail:like' content.pk %}">いいね！</a>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
    <link rel="stylesheet" href="/static/materialize.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="/static/materialize.js">


</head>
<body>


<h1>Welcome Django!!</h1>

<div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-action">
          <a href="{% url 'mail:mail' %}">This is a link</a>
        </div>
      </div>
    </div>
  </div>

<section id="send_box" class="send_box">
 <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">mode_edit</i>
          <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
          <label for="icon_prefix2"></label>
        </div>
      </div>
    </form>
  </div>
</section>

{% if not request.user.is_authenticated %}
<div>
<a href="{%url 'account_login'%}">ログイン画面へ</a>
</div>

<div>
<a href="{% url 'twitter_login' %}">Twitterでログイン</a>
</div>
{% endif %}



<div>
<a href="{%url 'account_logout'%}">ログアウト</a>
</div>






</body>
</html>

templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>This is mail page!!</h1>


<h2>受信メッセージ</h2>
 {% for content in mails_list %}
     <h3>title: {{ content.title }}</h3>
     <p>text: {{ content.text }}</p>
     <p>likes: {{ content.like_counter }}</p>
     <p><a href="{% url 'mail:detail' content.pk %}">詳細</a></p>
 {% endfor %}

<div>
<a href="{%url 'account_logout'%}">ログアウト</a>
</div>





</body>
</html>